apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $CI_ENVIRONMENT_SLUG-reports
  namespace: $KUBE_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  annotations:
    app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
    app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
  labels:
    app: $CI_ENVIRONMENT_SLUG
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      name: $CI_ENVIRONMENT_SLUG
  template:
    metadata:
      annotations:
        app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
        app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
      labels:
        name: $CI_ENVIRONMENT_SLUG
        app: $CI_ENVIRONMENT_SLUG
    spec:
      containers:
      - name: app
        image: $CI_REGISTRY_IMAGE:$CI_REGISTRY_TAG
        ports:
        - name: web
          containerPort: $HTTP_PORT
        volumeMounts:
        - name: reports-storage
          mountPath: /usr/share/nginx/html
        livenessProbe:
          httpGet:
            path: /
            port: $HTTP_PORT
          initialDelaySeconds: 15
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: $HTTP_PORT
          initialDelaySeconds: 5
          timeoutSeconds: 15
        resources:
          requests:
            memory: 50Mi
          limits:
            memory: 75Mi
      volumes:
      - name: reports-storage
        persistentVolumeClaim:
          claimName: $CI_ENVIRONMENT_SLUG-reports
